-- Faculty substitution / class shifting (date-specific overrides)

CREATE TABLE IF NOT EXISTS ap_faculty_substitution_details (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  request_id BIGINT UNSIGNED NOT NULL,
  session_date DATE NOT NULL,
  timetable_entry_id INT UNSIGNED NOT NULL,
  plan_id INT UNSIGNED NOT NULL,
  class_session_id BIGINT UNSIGNED NULL,
  college_id INT NOT NULL,
  course_id INT NOT NULL,
  branch_id INT NOT NULL,
  batch VARCHAR(32) NOT NULL,
  year_of_study INT NULL,
  semester_number INT NULL,
  section_name VARCHAR(64) NOT NULL,
  timing_slot_id INT UNSIGNED NOT NULL,
  subject_id INT NULL,
  subject_code VARCHAR(64) NULL,
  subject_name VARCHAR(255) NULL,
  room_label VARCHAR(128) NULL,
  original_faculty_staff_link_id INT UNSIGNED NOT NULL,
  replacement_faculty_staff_link_id INT UNSIGNED NOT NULL,
  reason TEXT NOT NULL,
  execution_status ENUM('pending', 'applied', 'failed', 'cancelled') NOT NULL DEFAULT 'pending',
  execution_error TEXT NULL,
  applied_at DATETIME NULL,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_substitution_request (request_id),
  KEY idx_substitution_date_slot (session_date, timing_slot_id, branch_id, section_name),
  KEY idx_substitution_original_faculty (original_faculty_staff_link_id, session_date),
  KEY idx_substitution_replacement_faculty (replacement_faculty_staff_link_id, session_date),
  CONSTRAINT fk_fsd_request FOREIGN KEY (request_id) REFERENCES ap_requests(id),
  CONSTRAINT fk_fsd_entry FOREIGN KEY (timetable_entry_id) REFERENCES ap_timetable_entries(id),
  CONSTRAINT fk_fsd_plan FOREIGN KEY (plan_id) REFERENCES ap_timetable_plans(id),
  CONSTRAINT fk_fsd_original_faculty FOREIGN KEY (original_faculty_staff_link_id) REFERENCES ap_staff_link(id),
  CONSTRAINT fk_fsd_replacement_faculty FOREIGN KEY (replacement_faculty_staff_link_id) REFERENCES ap_staff_link(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ap_class_session_substitutions (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  request_id BIGINT UNSIGNED NOT NULL,
  class_session_id BIGINT UNSIGNED NOT NULL,
  session_date DATE NOT NULL,
  timetable_entry_id INT UNSIGNED NOT NULL,
  original_faculty_staff_link_id INT UNSIGNED NOT NULL,
  replacement_faculty_staff_link_id INT UNSIGNED NOT NULL,
  status ENUM('active', 'reversed') NOT NULL DEFAULT 'active',
  applied_at DATETIME NOT NULL,
  applied_by_user_id BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_css_session_active (class_session_id, status),
  KEY idx_css_request (request_id),
  KEY idx_css_date_replacement (session_date, replacement_faculty_staff_link_id),
  CONSTRAINT fk_css_request FOREIGN KEY (request_id) REFERENCES ap_requests(id),
  CONSTRAINT fk_css_session FOREIGN KEY (class_session_id) REFERENCES ap_class_sessions(id),
  CONSTRAINT fk_css_entry FOREIGN KEY (timetable_entry_id) REFERENCES ap_timetable_entries(id),
  CONSTRAINT fk_css_original FOREIGN KEY (original_faculty_staff_link_id) REFERENCES ap_staff_link(id),
  CONSTRAINT fk_css_replacement FOREIGN KEY (replacement_faculty_staff_link_id) REFERENCES ap_staff_link(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
